"""Connector — Git/GitHub Integration for Loop Engineering Practice Project 8.

The connector handles shipping validated changes. For this project, "shipping"
means creating a Git branch with the changelog draft and optionally opening
a pull request (via GitHub CLI if available). No auto-merge; human review required.

Key principle: Maker output must pass checker before ANY connector action.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Optional
import subprocess
import os
import shutil

from .checker import CheckResult
from .maker import MakerResult


@dataclass(frozen=True)
class ConnectorConfig:
    """Configuration for the connector."""
    repo_root: Path
    branch_prefix: str = "changelog-draft/"
    create_pr: bool = False  # Requires gh CLI
    pr_title_prefix: str = "[Draft] Changelog Update"
    pr_body_template: str = "Automated changelog draft from commits since last run.\n\n---\n*Generated by Loop Engineering Project 8*"


@dataclass(frozen=True)
class ConnectorResult:
    """Result of the connector phase."""
    shipped: bool
    branch_name: Optional[str]
    pr_url: Optional[str]
    message: str
    needs_human: bool


def run_git(repo_root: Path, *args: str, capture=True) -> subprocess.CompletedProcess:
    """Run a git command in the repository."""
    return subprocess.run(
        ["git", *args],
        cwd=repo_root,
        capture_output=capture,
        text=True,
    )


def get_current_branch(repo_root: Path) -> str:
    """Get the current branch name."""
    result = run_git(repo_root, "branch", "--show-current")
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def get_default_branch(repo_root: Path) -> str:
    """Detect the default branch (main/master) from origin/HEAD."""
    result = run_git(repo_root, "symbolic-ref", "refs/remotes/origin/HEAD")
    if result.returncode == 0:
        # Output: refs/remotes/origin/main
        return result.stdout.strip().split("/")[-1]
    # Fallback: check local branches
    result = run_git(repo_root, "branch", "--list", "main")
    if result.returncode == 0 and result.stdout.strip():
        return "main"
    return "master"


def branch_exists(repo_root: Path, branch_name: str) -> bool:
    """Check if a branch exists locally."""
    result = run_git(repo_root, "rev-parse", "--verify", branch_name)
    return result.returncode == 0


def create_branch(repo_root: Path, branch_name: str, base_branch: Optional[str] = None) -> bool:
    """Create a new branch from base_branch."""
    if base_branch is None:
        base_branch = get_default_branch(repo_root)
    # Fetch latest
    run_git(repo_root, "fetch", "origin", base_branch)
    # Create branch
    result = run_git(repo_root, "checkout", "-b", branch_name, f"origin/{base_branch}")
    return result.returncode == 0


def commit_changelog(repo_root: Path, changelog_path: Path, branch_name: str, commit_msg: str) -> bool:
    """Copy changelog to repo and commit it."""
    # Copy to repo root as CHANGELOG.draft.md (not overwriting real CHANGELOG.md)
    dest = repo_root / "CHANGELOG.draft.md"
    shutil.copy2(changelog_path, dest)

    # Stage and commit
    run_git(repo_root, "add", "CHANGELOG.draft.md")
    result = run_git(repo_root, "commit", "-m", commit_msg)
    return result.returncode == 0


def push_branch(repo_root: Path, branch_name: str) -> bool:
    """Push branch to origin."""
    result = run_git(repo_root, "push", "-u", "origin", branch_name)
    return result.returncode == 0


def create_pull_request(repo_root: Path, config: ConnectorConfig, branch_name: str, changelog_hash: str) -> Optional[str]:
    """Create a pull request using GitHub CLI (gh). Returns PR URL or None."""
    # Check if gh is available
    if shutil.which("gh") is None:
        return None

    base_branch = get_default_branch(repo_root)
    title = f"{config.pr_title_prefix} ({changelog_hash[:8]})"
    body = config.pr_body_template

    result = subprocess.run(
        ["gh", "pr", "create", "--title", title, "--body", body, "--head", branch_name, "--base", base_branch],
        cwd=repo_root,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    return None


def run_connector(
    config: ConnectorConfig,
    maker_result: MakerResult,
    check_result: CheckResult,
) -> ConnectorResult:
    """Execute the connector phase: ship validated changes.

    PRECONDITION: check_result.passed must be True.
    """
    if not check_result.passed:
        return ConnectorResult(
            shipped=False,
            branch_name=None,
            pr_url=None,
            message="Checker failed - connector aborted",
            needs_human=True,
        )

    # Generate branch name from changelog hash
    branch_name = f"{config.branch_prefix}{check_result.changelog_hash[:8]}"

    # Check if branch already exists (idempotency)
    if branch_exists(config.repo_root, branch_name):
        return ConnectorResult(
            shipped=False,
            branch_name=branch_name,
            pr_url=None,
            message=f"Branch {branch_name} already exists - skipping (idempotent)",
            needs_human=False,
        )

    # Create branch (auto-detect default branch)
    if not create_branch(config.repo_root, branch_name):
        return ConnectorResult(
            shipped=False,
            branch_name=None,
            pr_url=None,
            message="Failed to create branch",
            needs_human=True,
        )

    # Commit changelog
    commit_msg = f"chore: changelog draft {check_result.changelog_hash[:8]}\n\nAuto-generated by Loop Project 8"
    if not commit_changelog(config.repo_root, maker_result.changelog_path, branch_name, commit_msg):
        return ConnectorResult(
            shipped=False,
            branch_name=branch_name,
            pr_url=None,
            message="Failed to commit changelog",
            needs_human=True,
        )

    # Push branch
    if not push_branch(config.repo_root, branch_name):
        return ConnectorResult(
            shipped=False,
            branch_name=branch_name,
            pr_url=None,
            message="Failed to push branch",
            needs_human=True,
        )

    # Optionally create PR
    pr_url = None
    if config.create_pr:
        pr_url = create_pull_request(config, config, branch_name, check_result.changelog_hash)

    message = f"Created branch {branch_name}"
    if pr_url:
        message += f" and PR: {pr_url}"
    else:
        message += " (PR creation skipped or failed - needs human)"

    return ConnectorResult(
        shipped=True,
        branch_name=branch_name,
        pr_url=pr_url,
        message=message,
        needs_human=pr_url is None,  # Needs human if no PR created
    )


if __name__ == "__main__":
    print("Connector module - not meant to run directly")