"""Dream Maker — Produces Improvement Proposals for Dream Loop.

The maker takes the skill analysis result and produces concrete proposal artifacts
(PR descriptions, diffs) for the checker to validate.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional
import tempfile
import os

from dream_skill import DreamConfig, SkillResult, ProposedChange
from dream_spine import get_dreaming_state_path


@dataclass(frozen=True)
class DreamMakerConfig:
    """Configuration for the dream maker."""
    skill_result: SkillResult
    proposal_dir: Path  # Where to write proposal artifacts
    project8_root: Path  # Root of Project 8 for relative paths


@dataclass(frozen=True)
class ProposalArtifact:
    """A single proposal artifact ready for PR creation."""
    branch_name: str
    pr_title: str
    pr_body: str
    diff: str
    target_file: str
    change_type: str


@dataclass(frozen=True)
class MakerResult:
    """Result of the maker phase."""
    artifacts: List[ProposalArtifact]
    proposal_dir: Path
    tokens_used: int


def create_proposal_artifact(
    proposal: ProposedChange,
    project8_root: Path,
    config: DreamConfig,
) -> ProposalArtifact:
    """Create a PR-ready artifact from a proposed change."""
    # Generate branch name: claude/fix-<hash> or claude/delete-<hash>
    prefix = "fix" if proposal.change_type == "modify" else "delete"
    branch_name = f"claude/{prefix}-{proposal.proposal_hash}"
    
    # Generate PR title
    action = "Fix" if proposal.change_type == "modify" else "Remove"
    pr_title = f"{action}: {proposal.description}"
    
    # Generate PR body with evidence
    rel_path = proposal.file_path
    try:
        rel_path = proposal.file_path.relative_to(project8_root)
    except ValueError:
        pass
    
    pr_body = f"""## Automated Improvement Proposal (Dream Loop)

**Change Type:** {proposal.change_type.capitalize()}
**Target File:** `{rel_path}`

### Evidence
{proposal.evidence}

### Proposed Change
```diff
{proposal.diff}
```

### Validation
- [ ] Maker-checker validation passed
- [ ] Evidence cited with exact run dates and frequency
- [ ] Smallest possible change to address the issue
- [ ] No direct modification of rules files (PR only)

---
*Generated by Loop Engineering Project 12 — Dream Loop*
"""
    
    return ProposalArtifact(
        branch_name=branch_name,
        pr_title=pr_title,
        pr_body=pr_body,
        diff=proposal.diff,
        target_file=str(rel_path),
        change_type=proposal.change_type,
    )


def write_proposal_artifacts(artifacts: List[ProposalArtifact], proposal_dir: Path) -> None:
    """Write proposal artifacts to the proposal directory."""
    proposal_dir.mkdir(parents=True, exist_ok=True)
    
    for i, artifact in enumerate(artifacts):
        # Write diff
        diff_path = proposal_dir / f"proposal_{i}_{artifact.change_type}.diff"
        diff_path.write_text(artifact.diff, encoding="utf-8")
        
        # Write PR description
        pr_path = proposal_dir / f"proposal_{i}_{artifact.change_type}_pr.md"
        pr_path.write_text(artifact.pr_body, encoding="utf-8")


def run_maker(config: DreamMakerConfig) -> MakerResult:
    """Execute the maker phase: produce proposal artifacts from skill result."""
    artifacts = []
    
    # Reconstruct DreamConfig for create_proposal_artifact
    dream_config = DreamConfig(
        progress_md_path=config.project8_root / "progress.md",
        dreaming_state_path=get_dreaming_state_path(),
        rules_files=[
            config.project8_root / "src" / "skill.py",
            config.project8_root / "src" / "connector.py",
            config.project8_root / "src" / "checker.py",
            config.project8_root / "src" / "budget.py",
            config.project8_root / "src" / "maker.py",
        ],
    )
    
    # Create artifacts for proposals
    for proposal in config.skill_result.proposals:
        artifact = create_proposal_artifact(proposal, config.project8_root, dream_config)
        artifacts.append(artifact)
    
    # Create artifacts for deletions
    for deletion in config.skill_result.deletions:
        artifact = create_proposal_artifact(deletion, config.project8_root, dream_config)
        artifacts.append(artifact)
    
    # Write artifacts
    write_proposal_artifacts(artifacts, config.proposal_dir)
    
    # Estimate tokens
    tokens = sum(len(a.pr_body) + len(a.diff) for a in artifacts) // 4 + 100
    
    return MakerResult(
        artifacts=artifacts,
        proposal_dir=config.proposal_dir,
        tokens_used=tokens,
    )


if __name__ == "__main__":
    print("Dream Maker module - not meant to run directly")